# So, you want to update the Rust toolchain...

# Besides making sure the code compiles (duh) and the tests/clippy pass (obviously)
# Please note that you'll have to update all the toolchain references in the codebase!
# AND build new docker images for:
# - rust_tari-build-with-deps
# - rust-ndk
# AND update the action-buildlibs dockerfile.


# Hours spent updating the Rust Toolchain = 8
# other places to check:
# - the CI files in .github folder
# - the Makefile in base_layer/key_manager/Makefile
[toolchain]
# 1.78 causes a mempory alignment panic in the version of wasmer we use. For now we'll lock to 1.77.
# https://github.com/wasmerio/wasmer/blob/2.3.0/lib/vm/src/instance/mod.rs#L968
# Error: unsafe precondition(s) violated: ptr::copy_nonoverlapping requires that both pointer arguments are aligned and non-null and the specified memory ranges do not overlap
channel = "1.77"
